name: screenshot_callback_example
description: Demonstrates how to use the screenshot_callback plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.8
  image_downloader: ^0.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  screenshot_callback:
    path: ../

flutter:
  uses-material-design: true