name: screenshot_callback_example
description: Demonstrates how to use the screenshot_callback plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.4
  screenshot_callback:
    git:
      url: https://github.com/windows7lake/flutter_screenshot_callback.git

dev_dependencies:
  flutter_test:
    sdk: flutter

#  screenshot_callback:
#    path: ../

flutter:
  uses-material-design: true